# Use the official ASP.NET Core image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80


FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "senior-devops-assessment.csproj"
RUN dotnet build "senior-devops-assessment.csproj" -c Release -o /app/build


FROM build AS publish
RUN dotnet publish "senior-devops-assessment.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "senior-devops-assessment.dll"]